Basis-Theory/basis-theory-react

- package.json
- yarn.lock
Pins Basis Theory JS SDK version
> fix: pin basis-theory-js dependency

- .github/CODEOWNERS
> chore(ENG-2473): update codeowners

- package.json
- yarn.lock
Bumps Basis Theory dependencies
> fix: bump basis-theory dependencies

- package.json
- src/core/index.ts
- yarn.lock
> fix: export common errors

- package.json
- src/core/BasisTheoryReact.ts
- src/core/index.ts
- src/core/types.ts
- src/core/useBasisTheory.ts
- src/elements/CardElement.tsx
- src/elements/TextElement.tsx
- src/elements/useBasisTheoryValue.ts
- src/elements/useElement.ts
- src/elements/useListener.ts
- test/core/BasisTheoryReact.test.ts
- test/core/useBasisTheory.test.tsx
- test/elements/CardElement.test.tsx
- test/elements/TextElement.test.tsx
- test/elements/useElement.test.ts
- test/elements/useListener.test.ts
- yarn.lock
Updates Basis Theory dependencies to converge interfaces at the SDK
> feat: update Basis Theory dependencies

- package.json
- src/core/BasisTheoryReact.ts
- src/core/types.ts
- src/elements/CardElement.tsx
- src/elements/TextElement.tsx
- src/elements/useElement.ts
- src/elements/useListener.ts
- test/core/BasisTheoryReact.test.ts
- test/elements/useListener.test.ts
- yarn.lock
Adds `cardBrand` to CardElement change event
Throws `Error` when element has not been found by `BasisTheoryReact.getElement`
> feat: add cardBrand to CardElement change event

- .github/workflows/release.yml
- jest.config.js
- package.json
- src/core/BasisTheoryProvider.tsx
- src/core/BasisTheoryReact.ts
- src/core/index.ts
- src/core/useBasisTheory.ts
- src/elements/CardElement.tsx
- src/elements/CardExpirationDateElement.tsx
- src/elements/CardNumberElement.tsx
- src/elements/CardVerificationCodeElement.tsx
- src/elements/index.ts
- src/elements/useBasisTheoryValue.ts
- src/elements/useElement.ts
- src/types.ts
- test/core/BasisTheoryReact.test.ts
- test/elements/CardExpirationDateElement.test.tsx
- test/elements/CardNumberElement.test.tsx
- test/elements/CardVerificationCodeElement.test.tsx
- test/elements/__snapshots__/CardExpirationDateElement.test.tsx.snap
- test/elements/__snapshots__/CardNumberElement.test.tsx.snap
- test/elements/__snapshots__/CardVerificationCodeElement.test.tsx.snap
- test/elements/useElement.test.ts
- yarn.lock
Adds `CardExpirationDateElement`, `CardVerificationCodeElement` and `CardNumberElement`
> feat: add `CardExpirationDateElement`, `CardVerificationCodeElement` and `CardNumberElement`

- package.json
- src/elements/CardElement.tsx
- src/elements/CardExpirationDateElement.tsx
- src/elements/CardNumberElement.tsx
- src/elements/CardVerificationCodeElement.tsx
- src/elements/TextElement.tsx
- test/elements/CardElement.test.tsx
- test/elements/CardExpirationDateElement.test.tsx
- test/elements/CardNumberElement.test.tsx
- test/elements/CardVerificationCodeElement.test.tsx
- test/elements/TextElement.test.tsx
- yarn.lock
Adds `autocomplete` option to Elements.
> feat: add autocomplete to elements

- package.json
- yarn.lock
- Bump js sdk version that removes atomics
> chore: bump js sdk version

- src/elements/CardElement.tsx
- src/elements/CardExpirationDateElement.tsx
- src/elements/CardNumberElement.tsx
- src/elements/CardVerificationCodeElement.tsx
- src/elements/TextElement.tsx
- src/elements/useElement.ts
- test/elements/CardElement.test.tsx
- test/elements/CardExpirationDateElement.test.tsx
- test/elements/CardNumberElement.test.tsx
- test/elements/CardVerificationCodeElement.test.tsx
- test/elements/TextElement.test.tsx
- test/elements/useElement.test.ts
- Adds `wrapperRef` to all elements to certify the wrapper `<div>` is in the DOM before trying to mount the element.
> fix: add wrapper ref to wrapper div and use element hook

- src/elements/useElement.ts
Allow React to unmount the Element naturally
> fix: remove unmount logic and use internal element ref

- src/elements/CardElement.tsx
- src/elements/CardExpirationDateElement.tsx
- src/elements/CardNumberElement.tsx
- src/elements/CardVerificationCodeElement.tsx
- src/elements/TextElement.tsx
- src/elements/useElement.ts
- test/elements/CardElement.test.tsx
- test/elements/CardExpirationDateElement.test.tsx
- test/elements/CardNumberElement.test.tsx
- test/elements/CardVerificationCodeElement.test.tsx
- test/elements/TextElement.test.tsx
- test/elements/useElement.test.ts
- Introduces forwarded `refs` for elements
> feat: introduce refs

- package.json
- yarn.lock
> fix: bumping js sdk

- src/core/BasisTheoryReact.ts
- Marks `getElement` as deprecated
> chore: mark getElement as deprecated

- package.json
- src/elements/CardElement.tsx
- src/elements/CardExpirationDateElement.tsx
- src/elements/CardNumberElement.tsx
- src/elements/CardVerificationCodeElement.tsx
- src/elements/TextElement.tsx
- test/elements/CardElement.test.tsx
- test/elements/CardExpirationDateElement.test.tsx
- test/elements/CardNumberElement.test.tsx
- test/elements/CardVerificationCodeElement.test.tsx
- test/elements/TextElement.test.tsx
- yarn.lock
Matches inherited types from the SDK
> fix: match inherited SDK types

- package.json
- test/core/useBasisTheory.test.tsx
- test/core/useBasisTheoryValue.test.ts
- test/elements/useElement.test.ts
- test/elements/useListener.test.ts
- yarn.lock
> feat: Eng 3700 support react 18

- package.json
- yarn.lock
- update `basis-theory-js`
- update `basis-theory/eslint-config`
> chore: bump basis-theory packages

- package.json
- src/elements/CardElement.tsx
- src/elements/CardExpirationDateElement.tsx
- src/elements/CardNumberElement.tsx
- src/elements/CardVerificationCodeElement.tsx
- test/elements/CardElement.test.tsx
- test/elements/CardExpirationDateElement.test.tsx
- test/elements/CardNumberElement.test.tsx
- test/elements/CardVerificationCodeElement.test.tsx
- yarn.lock
- update all card components interfaces to support `validateOnChange`
> feat: add support for validateOnChange

- package.json
- yarn.lock
- Bumps BTJS to add elements `metadata` types
> feat: bump btjs to add elements metadata

- package.json
- yarn.lock
> fix: bump btjs

- src/elements/CardElement.tsx
- src/elements/CardExpirationDateElement.tsx
- src/elements/CardNumberElement.tsx
- src/elements/CardVerificationCodeElement.tsx
- test/elements/CardElement.test.tsx
- test/elements/CardExpirationDateElement.test.tsx
- test/elements/CardNumberElement.test.tsx
- test/elements/CardVerificationCodeElement.test.tsx
- add enableCopy prop to all card elements
- update tests
> feat: add enableCopy prop to all card elements

- .github/workflows/release.yml
- Internal notifications on deployments 
- [x ] Not Applicable
- [ x] Not Applicable
> add deploy notifications

- package.json
- yarn.lock
- upgrades btjs to the latest version
> feat: upgrade btjs

- src/core/useBasisTheory.ts
- fixes infinite loop when running into an error
> fix: fixes infinite loop when running into an error

- package.json
- yarn.lock
> fix: ugrade js sdk

- .github/workflows/pull-request.yml
- CHANGELOG.md
- package.json
- yarn.lock
> fix: upgrading CRA message and dependecies

- .github/workflows/release.yml
> fix: release build to 18 to support semantic

- jest.config.js
- package.json
- src/elements/CardElement.tsx
- src/elements/CardExpirationDateElement.tsx
- src/elements/CardNumberElement.tsx
- src/elements/CardVerificationCodeElement.tsx
- src/elements/TextElement.tsx
- test/elements/CardElement.test.tsx
- test/elements/CardExpirationDateElement.test.tsx
- test/elements/CardNumberElement.test.tsx
- test/elements/CardVerificationCodeElement.test.tsx
- test/elements/TextElement.test.tsx
- yarn.lock
- Adds readonly
- replaces ts-jest with swc/jest
> feat: adds readOnly

- package.json
- src/elements/CardElement.tsx
- src/elements/CardExpirationDateElement.tsx
- src/elements/CardNumberElement.tsx
- src/elements/CardVerificationCodeElement.tsx
- src/elements/TextElement.tsx
- test/elements/CardElement.test.tsx
- test/elements/CardExpirationDateElement.test.tsx
- test/elements/CardNumberElement.test.tsx
- test/elements/CardVerificationCodeElement.test.tsx
- test/elements/TextElement.test.tsx
- yarn.lock
> feat: adds inputMode

- README.md
> chore: updating api keys examples

- .github/workflows/pull-request.yml
- package.json
- yarn.lock
- Upgrade deps
- Add concurrency group so previous workflows are cancelled when same branch pushed.
> chore: upgrade deps and add concurrency group

- package.json
- src/core/index.ts
- src/elements/CardElement.tsx
- src/elements/CardNumberElement.tsx
- yarn.lock
- feat: update btjs
- feat: exposes default cardTypes from BTJS
- feat: adds support for custom cardTypes
> feat: adds support for custom cardTypes

- package.json
- src/elements/CardElement.tsx
- src/elements/CardNumberElement.tsx
- test/elements/CardElement.test.tsx
- test/elements/CardNumberElement.test.tsx
- yarn.lock
- feat: adds skipLuhnValidation
> feat: adds skipLuhnValidation

- package.json
- src/elements/TextElement.tsx
- test/elements/TextElement.test.tsx
- yarn.lock
- feat: adds maxLength to TextElement
> feat: adds maxLength to TextElement

- .github/workflows/release.yml
> chore: remove deprecated workflow step

- package.json
- src/elements/CardElement.tsx
- src/elements/CardExpirationDateElement.tsx
- src/elements/CardNumberElement.tsx
- src/elements/CardVerificationCodeElement.tsx
- src/elements/TextElement.tsx
- yarn.lock
- feat: add support for granular autocomplete values
> feat: add support for granular autocomplete values

- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- update to workflows for new secrets management
> chore: update workflows for new secrets management

- package.json
- yarn.lock
> feat: bump btjs

- package.json
- src/elements/CardElement.tsx
- yarn.lock
- feat: adds custom placeholder to card element
> feat: adds custom placeholder to card element

- package.json
- yarn.lock
> feat: bump btjs to add useSameOriginApi

- package.json
- yarn.lock
- Bump BT-JS, adding the `_debug` prop to `init`
> feat: bump btjs to add debug prop

- package.json
- yarn.lock
> fix: patch btjs

- src/elements/TextElement.tsx
- test/elements/TextElement.test.tsx
- fix(textelement): surface validate on change
> fix(textelement): surface validate on change

- README.md
- chore: deprecate package [skip ci]
> chore: deprecate package
